### PR TITLE
better ownable contract

### PR DESCRIPTION
**Pull request by naumenkogs**
Replacing ownable with a more conservative one as was discussed.

### CODE REVIEW

**Comment by expede** [comment]
Are we not able to use a contract from an npm dependency? Why copy/paste the dependency, basically?

**Comment by naumenkogs** [comment]
@expede 
I never thought about it. Having our dependencies is explicit and safe.

**Comment by naumenkogs** [comment]
What you're proposing is having an import in solidity "node_modules/open_zeppelin/contracts/Ownable.sol"?

At least for this repo I think it's good to have the dependency folder because it's easier to check what's in it for a reviewer of the reference implementation.

**Comment by expede** [comment]
>What you're proposing is having an import in solidity "node_modules/open_zeppelin/contracts/Ownable.sol"?

Yeah, exactly. If we pin OpenZeppelin to a certain version in `package.json` we get the same advantages. I'm not really bothered that much one way or another, but having this directory  this is more for us to test and maintain. If you're good to write or copy/paste tests for them then 👍

**Pull request merged**
